# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# 设置工作目录
WORKDIR /app

# 复制本地代码到镜像
COPY . .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 暴露端口（如需）
EXPOSE 3000 9000

# Set environment variables for MySQL (these can be overwritten with `docker run -e`)
ENV MYSQL_HOST=localhost
ENV MYSQL_PORT=3306
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=mcp_db
ENV MYSQL_ROLE=admin
ENV PYTHONPATH=/app/src

# Command to run the server
CMD ["python", "-m", "server.mcp.server_mysql"]